//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/24/2025 12:19:27 PM
namespace NS
{
    /// <summary>
    /// There are no comments for CustomerType in the schema.
    /// </summary>
    [global::System.Flags]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerType")]
    internal enum CustomerType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("None")]
        None = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Premium")]
        Premium = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("VIP")]
        VIP = 4
    }
}
