//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/24/2025 12:19:27 PM
namespace NS
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    internal static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::NS.Customer as global::NS.CustomerSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::NS.CustomerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NS.Customer> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::NS.CustomerSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::NS.Customer as global::NS.CustomerSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::NS.CustomerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NS.Customer> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::NS.CustomerSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::NS.Order as global::NS.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::NS.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NS.Order> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::NS.OrderSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::NS.Order as global::NS.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::NS.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NS.Order> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::NS.OrderSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// There are no comments for GetCustomerOrdersTotalAmount in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetCustomerOrdersTotalAmount")]
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<int> GetCustomerOrdersTotalAmount(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::NS.Customer> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuerySingle<int>("NS.GetCustomerOrdersTotalAmount", false);
        }
        /// <summary>
        /// There are no comments for GetCustomerByName in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetCustomerByName")]
        public static global::NS.CustomerSingle GetCustomerByName(this global::Microsoft.OData.Client.DataServiceQuery<global::NS.Customer> _source, string name)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::NS.CustomerSingle(_source.CreateFunctionQuerySingle<global::NS.Customer>("NS.GetCustomerByName", false, new global::Microsoft.OData.Client.UriOperationParameter("name", name)));
        }
    }
}
